In [1]:
import numpy as np

my_list = [2, 4, 8, 16]

#create array using a list
my_array = np.asarray(my_list)

print("Type: {}".format(type(my_array)))

Type: <class 'numpy.ndarray'>


### Array Arithmetic
No iterations needed

In [2]:
print(my_array + 2)

[ 4  6 10 18]


In [3]:
print(my_array - 1)

[ 1  3  7 15]


In [4]:
print(my_array * 2)

[ 4  8 16 32]


In [5]:
print(my_array / 3 )

[0.66666667 1.33333333 2.66666667 5.33333333]


# Create NumPy Arrays

In [6]:
second_array = np.zeros(4) + 3
print(second_array)
print(my_array - second_array)
print(my_array / second_array)

[3. 3. 3. 3.]
[-1.  1.  5. 13.]
[0.66666667 1.33333333 2.66666667 5.33333333]


In [7]:
second_array = np.ones(4) + 3
print(second_array)
print(my_array - second_array)
print(my_array / second_array)

[4. 4. 4. 4.]
[-2.  0.  4. 12.]
[0.5 1.  2.  4. ]


In [8]:
second_array = np.identity(4)
print(second_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
second_array = second_array + 3
print(second_array)
print(my_array - second_array)

[[4. 3. 3. 3.]
 [3. 4. 3. 3.]
 [3. 3. 4. 3.]
 [3. 3. 3. 4.]]
[[-2.  1.  5. 13.]
 [-1.  0.  5. 13.]
 [-1.  1.  4. 13.]
 [-1.  1.  5. 12.]]


In [10]:
x = np.arange(3,7,0.5)
print(x)

[3.  3.5 4.  4.5 5.  5.5 6.  6.5]


In [11]:
x = np.linspace(3,6.5, num=8)
print(x)

[3.  3.5 4.  4.5 5.  5.5 6.  6.5]


In [12]:
x = np.geomspace(1,625, num=5)
print(x)

[  1.   5.  25. 125. 625.]


In [13]:
#start at 10^3 and end at 10^4
x = np.logspace(3,4, num=5)
print(x)

[ 1000.          1778.27941004  3162.27766017  5623.4132519
 10000.        ]


In [14]:
x = np.logspace(np.log10(3) , np.log10(4) , num=5)
print(x)

[3.         3.2237098  3.46410162 3.72241944 4.        ]


### Compare Arrays Elements

In [15]:
x = np.array([1,2,3,4])
y = np.array([1,3,2,4])
print(x==y)
print(x<y)

[ True False False  True]
[False  True False False]


### Loical Array Comparision

In [16]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)

print(np.logical_or(x, y))
print(np.logical_and(x, y))

[ True  True False  True]
[False  True False False]


### Complex Comparision

In [17]:
x = np.array([12,16,57,11])
print(np.logical_or(x < 12, x>50))

[False False  True  True]


### Vectorized Math Functions

In [18]:
x = np.array([1, 2, 3,4 ])
print(np.exp(x))
print(np.log(x))
print(np.log10(x))
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[0.         0.30103    0.47712125 0.60205999]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# Reshaping Array

In [19]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [20]:
# Reshape 9 elements into 3 X 3 matrix
# Parameter is a tuple of (row, column)
x = x.reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# Transpose
y = np.arange(6).reshape((2,3))
print(x.T)
print(y)
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


# Summary Methods

In [22]:
x = np.arange(9).reshape((3,3))
# Summary across all axes
print("Sum: {}".format(np.sum(x)))
print("Minimum: {}".format(np.amin(x)))
print("Maximum: {}".format(np.amax(x)))
print("80 percentile: {}".format(np.percentile(x, 80)))

Sum: 36
Minimum: 0
Maximum: 8
80 percentile: 6.4


In [23]:
# Summary by rows (axis = 0 )
print("Sum: {}".format(np.sum(x, axis = 0)))
print("Minimum: {}".format(np.amin(x, axis = 0)))
print("Maximum: {}".format(np.amax(x, axis = 0)))
print("80 percentile: {}".format(np.percentile(x, 80, axis = 0)))

Sum: [ 9 12 15]
Minimum: [0 1 2]
Maximum: [6 7 8]
80 percentile: [4.8 5.8 6.8]


In [24]:
# Summary by columns (axis = 1 )
print("Sum: {}".format(np.sum(x, axis = 1)))
print("Minimum: {}".format(np.amin(x, axis = 1)))
print("Maximum: {}".format(np.amax(x, axis = 1)))
print("80 percentile: {}".format(np.percentile(x, 80, axis = 1)))

Sum: [ 3 12 21]
Minimum: [0 3 6]
Maximum: [2 5 8]
80 percentile: [1.6 4.6 7.6]


If values contain NaN then to ignore them and clculate aggregate values use folliwing:
* np.amin -> np.nanmin
* np.amax -> np.nanmax
* np.percentile -> np.nanpercentile

In [25]:
# Find index of min and max values
x = np.array([1,-21,3,-3])
print(np.argmax(x))
print(np.argmin(x))

2
1


### Statistical Functions

In [26]:
x = np.array([[2, 3, 5], [20, 12, 4]])
# Stats across all axes
print("Mean: {}".format(np.mean(x)))
print("Median: {}".format(np.median(x)))
print("Std. Dev.: {}".format(np.std(x)))

Mean: 7.666666666666667
Median: 4.5
Std. Dev.: 6.394442031083626


In [27]:
# Stats by rows (axis = 0 )
print("Mean: {}".format(np.mean(x, axis = 0)))
print("Median: {}".format(np.median(x, axis = 0)))
print("Std. Dev.: {}".format(np.std(x, axis = 0)))

Mean: [11.   7.5  4.5]
Median: [11.   7.5  4.5]
Std. Dev.: [9.  4.5 0.5]


In [28]:
# Stats by columns (axis = 1 )
print("Mean: {}".format(np.mean(x, axis = 1)))
print("Median: {}".format(np.median(x, axis = 1)))
print("Std. Dev.: {}".format(np.std(x, axis = 1)))

Mean: [ 3.33333333 12.        ]
Median: [ 3. 12.]
Std. Dev.: [1.24721913 6.53197265]


If values contain NaN then to ignore them and clculate aggregate values use folliwing:
* np.mean -> np.nanmean
* np.median -> np.nanmedian
* np.std -> np.nanstd