In [2]:
import numpy as np

# Create 4 X 4 array of ones
c = np.ones((4, 4))

# Cross Product
print(c*c)

# Dot Product
print(c.dot(c))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


# Stacking
Merging two arrays. In 2 dimension arrays think **vstack** as appending rows and **hstack** as appending columns


In [3]:
# Here we have two arrays with 5 column each.
y = np.arange(15).reshape(3,5)
x = np.arange(10).reshape(2,5)
print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
# Stack them
new_array = np.vstack((x,y))
print(new_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
# Here we have two arrays with 3 rows each.
y = np.arange(9).reshape(3,3)
x = np.arange(6).reshape(3,2)
print(x)
print(y)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Stack them horizontally
new_array = np.hstack((x,y))
print(new_array)

[[0 1 0 1 2]
 [2 3 3 4 5]
 [4 5 6 7 8]]


### Example of stacking
Lets say we have a dataset of 100 rows and 10 columns (features) and if we want to draaw staticstics per column, we can use stakcing to summarize the information.

To understand skewness and kurtosis mesures see: https://codeburst.io/2-important-statistics-terms-you-need-to-know-in-data-science-skewness-and-kurtosis-388fef94eeaa


In [14]:
from scipy import stats
x= np.random.rand(100,10)

#scipy stats method will derive all the statistics
n, min_max, mean, var, skew, kurt = stats.describe(x)

#now stack them vertically 
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))

#Print the statistics for all 10 columns
print(new_array.T)

[[ 0.48348444  0.09674714 -0.0207239  -1.34720052  0.00311088  0.99962794]
 [ 0.52093943  0.08032375 -0.11221435 -0.94207943  0.02065492  0.99963117]
 [ 0.46184178  0.08330569  0.18543054 -1.21318789  0.00657433  0.97897298]
 [ 0.5315323   0.07715898 -0.11152488 -1.20683201  0.02837209  0.99455791]
 [ 0.4905059   0.08106651  0.0740891  -1.21210961  0.03070341  0.99363069]
 [ 0.52553242  0.08234713 -0.22301843 -1.09017187  0.01383873  0.98535908]
 [ 0.44583226  0.08368623  0.39601575 -1.12130804  0.01019757  0.99278139]
 [ 0.50466555  0.08202902 -0.09610417 -1.13779545  0.00491567  0.99857987]
 [ 0.48990648  0.08876485  0.02158844 -1.28279764  0.0060192   0.99040873]
 [ 0.45006007  0.08083109  0.23006072 -1.14383884  0.01945353  0.99749261]]
