In [1]:
import numpy as np

#Simple List & Tuple Indexing
x = ["USA","France","Germany","India"]
y = ("India", 4, "China", 0)

print(x[1], y[2])

France China


### Simple slicing with 1-D Arrays

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[5]

5

In [4]:
x[-2] #from the end - its not 0 index

8

In [5]:
x[2:8] #Range ()

array([2, 3, 4, 5, 6, 7])

In [6]:
x[2:8:2] #Range with skip

array([2, 4, 6])

In [7]:
x[2:-2] #Range

array([2, 3, 4, 5, 6, 7])

### Multidim indexing

In [8]:
x = np.reshape(np.arange(16), (4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
x[1:3] #Range on first axis

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
x[:,1:3] #Range on first axis

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [12]:
x[1:3,1:3] #Range on both axes

array([[ 5,  6],
       [ 9, 10]])

In [13]:
x[[0,1,2],[0,1,3]]

array([ 0,  5, 11])

### Reshape/Resize
Resahpe doesnt change the original array
Resize changes the original array

In [14]:
x = np.reshape(np.arange(16), (4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.resize(x, (2,2))

array([[0, 1],
       [2, 3]])

In [17]:
np.resize(x, (6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [19]:
x.reshape((2,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

### Broadcast
NumPy has two rules for broadcasting: either the dimensions of the arrays are equal, or one of them is 1

In [23]:
from IPython.core.magic import register_cell_magic

@register_cell_magic('handle')
def handle(line, cell):
    try:
        exec(cell)
    except Exception as e:
        print(e)

x = np.reshape(np.arange(16), (4,4))
y = np.reshape(np.arange(6), (2,3))

%%handle
x + y #This will error

UsageError: Line magic function `%%handle` not found.


In [24]:
x = np.reshape(np.arange(16), (4,4))
y = np.arange(4)
x + y

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [26]:
x = np.arange(4).reshape(2,2)
y = np.arange(2) #default shape is (1,2)
x * y

array([[0, 1],
       [0, 3]])