In [4]:
import numpy as np

x = np.arange(6).reshape(3,2)
y = np.reshape(np.arange(10), (2,5)) #Alternate way of writing the reshape

print(x)
print(y)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
#Dot Product - syntax 1
np.dot(x, y)

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [6]:
#Dot Product - syntax 2
np.matmul(x, y)

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [8]:
#Dot Product - syntax 3
x@y

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

### Dot product for more than 2 matrix

In [9]:
from numpy.linalg import multi_dot
a = np.arange(12).reshape(4,3)
b = np.arange(15).reshape(3,5)
c = np.arange(25).reshape(5,5)

multi_dot([a, b, c])

array([[ 1700,  1855,  2010,  2165,  2320],
       [ 5300,  5770,  6240,  6710,  7180],
       [ 8900,  9685, 10470, 11255, 12040],
       [12500, 13600, 14700, 15800, 16900]])

In [10]:
np.dot(np.dot(a, b),c)

array([[ 1700,  1855,  2010,  2165,  2320],
       [ 5300,  5770,  6240,  6710,  7180],
       [ 8900,  9685, 10470, 11255, 12040],
       [12500, 13600, 14700, 15800, 16900]])

In [11]:
(a@b)@c

array([[ 1700,  1855,  2010,  2165,  2320],
       [ 5300,  5770,  6240,  6710,  7180],
       [ 8900,  9685, 10470, 11255, 12040],
       [12500, 13600, 14700, 15800, 16900]])

In [12]:
a.dot(b).dot(c)

array([[ 1700,  1855,  2010,  2165,  2320],
       [ 5300,  5770,  6240,  6710,  7180],
       [ 8900,  9685, 10470, 11255, 12040],
       [12500, 13600, 14700, 15800, 16900]])

In [13]:
import time

a = np.arange(120000).reshape(400, 300)
b = np.arange(150000).reshape(300, 500)
c = np.arange(200000).reshape(500, 400)

start = time.time()
multi_dot([a, b, c])
print('multi_dot took', time.time()-start, 'seconds')

start = time.time()
np.dot(np.dot(a, b),c)
print('np.dot took', time.time()-start, 'seconds')

start = time.time()
(a@b)@c
print('@ took', time.time()-start, 'seconds')

multi_dot took 0.11596083641052246 seconds
np.dot took 0.11885404586791992 seconds
@ took 0.1293189525604248 seconds


### Inner/Outer Products

In [14]:
a = np.arange(9).reshape(3,3)
b = np.arange(3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [20]:
np.inner(a,b)

array([ 5, 14, 23])

In [17]:
np.outer(b,a)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16]])

In [18]:
np.outer(a,b)

array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14],
       [ 0,  8, 16]])

### Tensor Dot Product

In [21]:
a = np.arange(12).reshape(2,3,2)
b = np.arange(48).reshape(3,2,8)
c = np.tensordot(a, b, axes =([1,0], [0,1]))
c

array([[ 800,  830,  860,  890,  920,  950,  980, 1010],
       [ 920,  956,  992, 1028, 1064, 1100, 1136, 1172]])