In [2]:
import numpy as np
from sklearn import decomposition, datasets
from sklearn.preprocessing import StandardScaler

data = datasets.load_breast_cancer()
cancer = data.data
cancer = StandardScaler().fit_transform(cancer) # mean=0; variance=1; z = (value - mean)/(standad deviation)
cancer.shape

(569, 30)

In [5]:
before = data.data
before[:10, :1] #First 10 rows 1st column

array([[17.99],
       [20.57],
       [19.69],
       [11.42],
       [20.29],
       [12.45],
       [18.25],
       [13.71],
       [13.  ],
       [12.46]])

In [6]:
cancer[:10, :1] #First 10 rows 1st column

array([[ 1.09706398],
       [ 1.82982061],
       [ 1.57988811],
       [-0.76890929],
       [ 1.75029663],
       [-0.47637467],
       [ 1.17090767],
       [-0.11851678],
       [-0.32016686],
       [-0.47353452]])

Calculate covariance matrix in order to calculate eigenvale and eigenvector

In [7]:
covariance_matrix= np.cov(cancer, rowvar=False) #rovar is analysis space - we are doing per column
covariance_matrix.shape

(30, 30)

In [30]:
eig_val_cov, eig_vec_cov = np.linalg.eig(covariance_matrix)
eig_pairs = [(np.abs(eig_val_cov[i]), eig_vec_cov[:,i]) for i in range(len(eig_val_cov))]

sorted_pairs = eig_pairs.sort(key=lambda x: x[0], reverse=True)
for i in eig_pairs:
    print(i[0])

13.304990794374563
5.701374603726144
2.8229101550062303
1.9841275177301978
1.6516332423301194
1.2094822398029734
0.6764088817009056
0.47745625468950725
0.4176287821078174
0.35131087488173407
0.2944331534911643
0.261621161366121
0.24178242132831412
0.15728614921759332
0.0943006956010556
0.08000340447737729
0.059503613530432396
0.05271142221014806
0.049564700212981545
0.031214260553066586
0.030025663090428402
0.027487711338904378
0.024383691354590994
0.018086793984305433
0.015508527134418687
0.008192037117607095
0.006912612579184526
0.0015921360011973828
0.0007501214127189963
0.00013327905666413948


In [31]:
eig_pairs[0]

(13.304990794374563,
 array([0.21890244, 0.10372458, 0.22753729, 0.22099499, 0.14258969,
        0.23928535, 0.25840048, 0.26085376, 0.13816696, 0.06436335,
        0.20597878, 0.01742803, 0.21132592, 0.20286964, 0.01453145,
        0.17039345, 0.15358979, 0.1834174 , 0.04249842, 0.10256832,
        0.22799663, 0.10446933, 0.23663968, 0.22487053, 0.12795256,
        0.21009588, 0.22876753, 0.25088597, 0.12290456, 0.13178394]))

Higher the eigenvalue for the column more relevant it is to the distribution. In above example first 2 values have most relevance rest can be dropped to reduce dimenstionality.

In [33]:
matrix_w = np.hstack([eig_pairs[0][1].reshape(30,1), eig_pairs[1][1].reshape(30,1)])
matrix_w.shape

(30, 2)

In [34]:
transformed = matrix_w.T.dot(cancer.T)
transformed = transformed.T

In [35]:
transformed.shape

(569, 2)

In [36]:
transformed[0]

array([9.19283683, 1.94858307])

### Using PCA

In [37]:
pca = decomposition.PCA(n_components=2)
x_std = StandardScaler().fit_transform(cancer)
pca.fit_transform(x_std)[0]

array([9.19283683, 1.94858307])