In [2]:
import numpy as np

x = np.array([2,5,9,0])

np.linalg.norm(x, ord=0)

3.0

In [3]:
np.linalg.norm(x, ord=1) #Manhattan norm

16.0

In [4]:
np.linalg.norm(x, ord=2) #default Euclidean

10.488088481701515

Mutliplying matrix with a vecotr stretches the vector. The norm of matrix reveal how much the matrix could possibly stretch a vector.

Find L1 and LInf

In [5]:
a = np.array([3,7,6,-2,-5,4,1,3,-14]).reshape(3,3)
a

array([[  3,   7,   6],
       [ -2,  -5,   4],
       [  1,   3, -14]])

In [11]:
np.linalg.norm(a, ord=1)

24.0

In [12]:
np.linalg.norm(a, ord=np.inf)

18.0

In [13]:
np.linalg.norm(a, ord=2)

15.8325010064061

Determinant is the scaling factor of a given matrix in linear transformation

In [14]:
A= np.array([2,3,1,4]).reshape(2,2)
A

array([[2, 3],
       [1, 4]])

In [15]:
np.linalg.det(A)

5.000000000000001

In [16]:
B= np.array([2,3,5,1,4,8,5,6,2]).reshape(3,3)
B

array([[2, 3, 5],
       [1, 4, 8],
       [5, 6, 2]])

In [17]:
np.linalg.det(B)

-36.0

Trace is the sum of diagonal elements

In [18]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.trace(a)

12

In [20]:
b = np.arange(27).reshape(3,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
np.trace(b)

array([36, 39, 42])